#!/usr/bin/env python2

from __future__ import absolute_import, division, print_function
import argparse
import sys

import nfldb

import nflfan


def log(*args, **kwargs):
    kwargs['file'] = sys.stderr
    print(*args, **kwargs)


if __name__ == '__main__':
    db = nfldb.connect()
    providers = nflfan.builtin_providers
    conf = nflfan.load_config(providers=providers)

    _, _, current_week = nfldb.current(db)

    parser = argparse.ArgumentParser(
        description='View your fantasy league on the command line.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    aa = parser.add_argument
    aa('-w', '--week', type=int, default=current_week,
       help='The week to view your fantasy league for.')
    args = parser.parse_args()
    assert 1 <= args.week <= 17

    for pname, leagues in conf.items():
        for lg in leagues:
            # scored = map(partial(nflfan.score_roster, db, lg.scoring), 
                         # lg.rosters(args.week)) 
            # for roster in scored: 
                # print(roster.owner) 
                # print(roster) 
                # print('-' * 79) 

            # players = [] 
            # for roster in lg.rosters(args.week): 
                # players += roster.players 
            # nflfan.score_players(db, lg.scoring, players) 

            mine = lg.me(lg.rosters(args.week))
            print(nflfan.score_roster(db, lg.scoring, mine))

