#!/usr/bin/env python2

from __future__ import absolute_import, division, print_function
from functools import partial
import os.path as path

import nfldb

import nflfan

db = nfldb.connect()
conf = nflfan.config()
player_search = partial(nflfan.player_search, db)

lg = conf['yahoo'][0]
prov = nflfan.provider.Yahoo(lg)

out = open(nflfan.json_path(prov.name), 'w+')
print(prov.json(player_search, 3, fobj=out))

# owners = prov.owners() 
# roster = prov.roster(player_search, owners[7], 3) 
# print(roster) 

